# Generated by Django 3.1.1 on 2020-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certno', models.CharField(max_length=200, null=True)),
                ('firma_adi', models.CharField(max_length=200, null=True)),
                ('standart', models.IntegerField(max_length=200, null=True)),
                ('belgelendirme_denetim_tarihi', models.DateTimeField(null=True)),
            ],
        ),
    ]
