# Generated by Django 3.1.1 on 2020-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='Adres',
            field=models.CharField(max_length=200,null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Aski_Tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Faks',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Iptal_Tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Kapsam',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Telefon',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Yeniden_Belgelendirme_Denetim_Tarihi',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='Yetkili_Kisi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='adt1',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='adt2',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='belge_bitiş_tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='ea',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='ilk_belgelendirme_tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='nace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='sertifika_tarihi',
            field=models.DateField(blank=True),
        ),
    ]
