# Generated by Django 3.1.1 on 2020-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200905_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Adres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Aski_Tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Iptal_Tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Yeniden_Belgelendirme_Denetim_Tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='adt1',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='adt2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='belge_bitiş_tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='belgelendirme_denetim_tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='ilk_belgelendirme_tarihi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='sertifika_tarihi',
            field=models.DateField(blank=True),
        ),
    ]
