# Generated by Django 3.1.1 on 2020-09-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200906_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Faks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Telefon',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='standart',
            field=models.IntegerField(null=True),
        ),
    ]
