# Generated by Django 3.1.1 on 2020-09-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200906_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Aski_Tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
