# Generated by Django 3.1.1 on 2020-09-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200906_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Yeniden_Belgelendirme_Denetim_Tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
