# Generated by Django 3.1.1 on 2020-09-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firma',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
