# Generated by Django 3.1.1 on 2020-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200908_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertifika_tarihi', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
