# Generated by Django 3.1.1 on 2020-09-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200908_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
