# Generated by Django 3.1.1 on 2020-09-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200911_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='Adres',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='Aski_Tarihi',
            new_name='Cert_Date',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='Faks',
            new_name='Fax',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='Iptal_Tarihi',
            new_name='Initial_Cert_Date',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='Telefon',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='Yeniden_Belgelendirme_Denetim_Tarihi',
            new_name='ReReg',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='Kapsam',
            new_name='Scope',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='ilk_belgelendirme_tarihi',
            new_name='Suspension_Date',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='sertifika_tarihi',
            new_name='Withdrawal_Date',
        ),
    ]
