# Generated by Django 3.1.1 on 2020-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200911_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='SA1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
