# Generated by Django 3.1.1 on 2020-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200912_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='SA1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
