# Generated by Django 3.1.1 on 2020-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_firma_sa1'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='SA1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
