# Generated by Django 3.1.1 on 2020-09-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_firma_sa1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firma',
            old_name='Certno',
            new_name='CertNo',
        ),
    ]
