# Generated by Django 3.1.1 on 2020-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200912_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Company_Name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Scope',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
