# Generated by Django 3.1.1 on 2020-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200912_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='nace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
