# Generated by Django 3.1.1 on 2020-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200912_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='SA1',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Scope',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nace',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
