# Generated by Django 3.1.1 on 2020-09-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200912_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='SA1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
