# Generated by Django 3.1.1 on 2020-09-13 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200913_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='Suspension_Date_Limit',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 14, 51, 39, 406316)),
        ),
    ]
