# Generated by Django 3.1.1 on 2020-09-13 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_firma_suspension_date_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Suspension_Date_Limit',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 13, 14, 52, 25, 932079)),
        ),
    ]
