# Generated by Django 3.1.1 on 2020-09-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200913_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='Suspension_Date_Limit',
        ),
    ]
