# Generated by Django 3.1.1 on 2020-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_firma_suspension_date_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='fbf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
