# Generated by Django 3.1.1 on 2020-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200916_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbf',
            name='BELGELENDİRME_KAPSAMINIZ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='DIŞ_KAYNAKLI_SÜREÇLER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='Danışmanlık_Hzmt_Aldınız_mı',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='Formu_Dolduran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='HARİÇ_TUTMALAR_ve_GEREKÇELER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='HİZMET_VERDİĞİNİZ_SEKTÖRLER_SAĞLAMIŞ_OLDUĞUNUZ_ÜRÜN_HİZMETLER_İLE_İLGİLİ_ÖRNEKLER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='Kiwadan_Nasıl_Haberdar_Oldunuz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='PROSES_VE_FAALİYETLERİNİZ_İNSAN_VE_TEKNİK_KAYNAKLAR_FONKSİYONLAR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='Tarih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='VARSA_MEVCUT_ÜRÜN_SİSTEM_BELGELERİ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbf',
            name='YASAL_ŞARTLAR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
