# Generated by Django 3.1.1 on 2020-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200917_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbf',
            name='BELGELENDİRME_KAPSAMINIZ',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
