# Generated by Django 3.1.1 on 2020-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200917_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbf',
            name='Çalışma_Saatleri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
