# Generated by Django 3.1.1 on 2020-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200918_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbf',
            name='Kapsam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
