# Generated by Django 3.1.1 on 2020-09-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_fbf_kapsam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbf',
            name='Kapsam',
        ),
    ]
