# Generated by Django 3.1.1 on 2020-09-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200920_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='Denetçi_Adı',
        ),
    ]
