# Generated by Django 3.1.1 on 2020-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200922_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Scope',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
