# Generated by Django 3.1.1 on 2020-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_event_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Denetçi_Adı',
        ),
    ]
