# Generated by Django 3.1.1 on 2020-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20200923_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Denetçi_Adı',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
