# Generated by Django 3.1.1 on 2020-09-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_event_denetçi_adı'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Denetci_9001',
            new_name='Kapsam_9001',
        ),
    ]
