# Generated by Django 3.1.1 on 2020-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_kapsam_9001_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denetci_9001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cert', models.IntegerField(null=True)),
                ('Personel_Adı', models.TextField(max_length=200, null=True)),
                ('ea', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Kapsam_9001',
        ),
    ]
