# Generated by Django 3.1.1 on 2020-09-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Denetci',
        ),
    ]
