# Generated by Django 3.1.1 on 2020-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20200927_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denetci',
            name='semester',
        ),
        migrations.AddField(
            model_name='denetci',
            name='Kapsam',
            field=models.CharField(choices=[('1', 'ISO9001'), ('2', 'ISO14001'), ('3', 'ISO22000'), ('4', 'ISO27001')], default='1', max_length=20),
        ),
    ]
