# Generated by Django 3.1.1 on 2020-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20200927_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('x', 'Male'), ('y', 'Female')], default='', max_length=60, verbose_name='gender')),
            ],
        ),
        migrations.DeleteModel(
            name='Denetci',
        ),
    ]
