# Generated by Django 3.1.1 on 2020-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20200927_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='fbf',
            name='ea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
