# Generated by Django 3.1.1 on 2020-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20200930_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='denetci_9001',
            name='denetim_suresi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
