# Generated by Django 3.1.1 on 2020-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20201002_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Personel_Adı',
        ),
    ]
