# Generated by Django 3.1.1 on 2020-10-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_event_personel_adı'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Personel_Adı',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.denetci_9001'),
        ),
    ]
