# Generated by Django 3.1.1 on 2020-10-02 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0058_event_personel_adı'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='Personel_Adı',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.denetci_9001'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user', 'Personel_Adı')},
        ),
    ]
