# Generated by Django 3.1.1 on 2020-10-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20201002_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'Personel_Adı')},
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
    ]
