# Generated by Django 3.1.1 on 2020-10-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20201003_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
