# Generated by Django 3.1.1 on 2020-10-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_remove_event_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('Personel_Adı',)},
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='event',
        ),
    ]
