# Generated by Django 3.1.1 on 2020-10-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20201003_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='abc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='accounts.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'Personel_Adı')},
        ),
    ]
