# Generated by Django 3.1.1 on 2020-10-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_control'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control',
            new_name='kontrol',
        ),
    ]
