# Generated by Django 3.1.1 on 2020-10-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20201004_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrol',
            name='Personel_Adı',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.denetci_9001'),
        ),
    ]
