# Generated by Django 3.1.1 on 2020-10-06 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20201006_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrol',
            name='end_time',
            field=models.ForeignKey(default=datetime.datetime, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.event'),
        ),
    ]
