# Generated by Django 3.1.1 on 2020-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_auto_20201006_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrol',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
