# Generated by Django 3.1.1 on 2020-10-19 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_auto_20201006_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrol',
            name='date1',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='kontrol',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
